### ISSUE TITLE
Not receiving any email on task failure

### ISSUE THREAD

**Issue by enpradeepkumar** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#12]
Hi Nick,

I have configured the tool with the server details and user details. Am able to receive the test message but not response from task failure. I have configured the email details in the custom properties under QMC

Below are the error and no email from task.

Time, LogLevel, Message
2018_01_08_01_49_36,Information,"Proxy: http://sae1dqlksp1.corp.stateauto.com"
2018_01_08_01_49_36,Error,"System.Exception: Couldnt connect to the server at http://sae1dqlksp1.corp.stateauto.com , check that the Proxy and QRS are running.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
"
2018_01_08_01_49_36,Information,"Returning Errorlevel 8"

I tried with all the possibilities in changing the Qliksense server name and SMTP email server.

But still it is not connecting

**Comment by enpradeepkumar** [comment]
Attached the config page and error screen 
[QlikSenseTasklog_2018_01_08_01_49_36.zip](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1612859/QlikSenseTasklog_2018_01_08_01_49_36.zip)

**Comment by NickAkincilar** [comment]
If the email goes out fine when you click test but you are getting this error then I would look in to user credentials. App uses windows authentication to connect to sense server so check the windows account that runs the scheduled task and make sure it has root admin rights or use your account for the windows task scheduler instead. 
-------- Original message --------From: enpradeepkumar <notifications@github.com> Date: 1/8/18  2:50 PM  (GMT-05:00) To: NickAkincilar/QlikSense-Task-Failure-Email-Alerts <QlikSense-Task-Failure-Email-Alerts@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [NickAkincilar/QlikSense-Task-Failure-Email-Alerts] Not receiving any
  email on task failure (#12) 
Hi Nick,
I have configured the tool with the server details and user details. Am able to receive the test message but not response from task failure. I have configured the email details in the custom properties under QMC
Below are the error and no email from task.
Time, LogLevel, Message

2018_01_08_01_49_36,Information,"Proxy: http://sae1dqlksp1.corp.stateauto.com"

2018_01_08_01_49_36,Error,"System.Exception: Couldnt connect to the server at http://sae1dqlksp1.corp.stateauto.com , check that the Proxy and QRS are running.

at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout)

at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)

at QlikSenseEmailAdmin.Program.Main(String[] args)

"

2018_01_08_01_49_36,Information,"Returning Errorlevel 8"
I tried with all the possibilities in changing the Qliksense server name and SMTP email server.
But still it is not connecting

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NickAkincilar/QlikSense-Task-Failure-Email-Alerts","title":"NickAkincilar/QlikSense-Task-Failure-Email-Alerts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Not receiving any email on task failure (#12)"}],"action":{"name":"View Issue","url":"https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/issues/12"}}}

**Comment by enpradeepkumar** [comment]
Thanks for your Quick reply Nick, Let me check by restarting the services
today and update you.

Connection status was successful till last week , However, I have not
received the task failure alert if any . Just received the Zero task
failure alert in all the logs.



Regards,
Pradeep

**Comment by minority360** [comment]
Hi Nick,
I could test connection to QS Ent, test email and created windows task scheduler from Alert Tool.
I had a failed reload task on qmc but the alert tool log returned following:

Time, LogLevel, Message
2018_01_16_10_04_04,Information,"Proxy: https://sift0035"
2018_01_16_10_04_07,Information,"Looking for Failed Tasks..."
2018_01_16_10_04_08,Information,"Found 0 Failed Tasks!"
2018_01_16_10_04_08,Information,"Returning Errorlevel 0"

I'm using QS November 2017 Patch 1. Please help and advise. 

many thanks,
kp

**Comment by enpradeepkumar** [comment]
Hi Nick,

Sorry to disturb you. I am still facing the same error (Connection
failed/Unsuccessful).Even though I am using the right URL and login
credentials .But still the problem persist.

Is there any other places like config files or .ini file , I have to make a
changes to get it done. Looking for your assistance.

Attached the config screenshot and error for your reference.

**Comment by enpradeepkumar** [comment]
> If the email goes out fine when you click test but you are getting this error then I would look in to user credentials. App uses windows authentication to connect to sense server so check the windows account that runs the scheduled task and make sure it has root admin rights or use your account for the windows task scheduler instead.  -------- Original message --------From: enpradeepkumar <notifications@github.com> Date: 1/8/18 2:50 PM (GMT-05:00) To: NickAkincilar/QlikSense-Task-Failure-Email-Alerts <QlikSense-Task-Failure-Email-Alerts@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [NickAkincilar/QlikSense-Task-Failure-Email-Alerts] Not receiving any   email on task failure (#12) Hi Nick, I have configured the tool with the server details and user details. Am able to receive the test message but not response from task failure. I have configured the email details in the custom properties under QMC Below are the error and no email from task. Time, LogLevel, Message 2018_01_08_01_49_36,Information,"Proxy: http://sae1dqlksp1.corp.stateauto.com" 2018_01_08_01_49_36,Error,"System.Exception: Couldnt connect to the server at http://sae1dqlksp1.corp.stateauto.com , check that the Proxy and QRS are running. at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout) at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger) at QlikSenseEmailAdmin.Program.Main(String[] args) " 2018_01_08_01_49_36,Information,"Returning Errorlevel 8" I tried with all the possibilities in changing the Qliksense server name and SMTP email server. But still it is not connecting — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NickAkincilar/QlikSense-Task-Failure-Email-Alerts","title":"NickAkincilar/QlikSense-Task-Failure-Email-Alerts","subtitle":"GitHub repository","main_image_url":"[https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open](https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png%22,%22avatar_image_url%22:%22https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Not](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22DESCRIPTION%22,%22message%22:%22Not) receiving any email on task failure (#12)"}],"action":{"name":"View Issue","url":"#12"}}}

Your comments, helps us to resolve the issue. Thank you
