### ISSUE TITLE
Email not getting triggered - error parsing log file

### ISSUE THREAD

**Issue by knightriderX3** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#2]
Hi!
The setup, QMC connection test and initial test mails worked fine.

This is excerpt from the log file:
2017_02_15_11_49_50,Information,"Looking for Failed Tasks..."
2017_02_15_11_49_50,Error,"Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetTaskByStatus(QSTaskStatus status)
   at QlikSenseEmailAdmin.Program.Main(String[] args)"
2017_02_15_11_49_50,Information,"Returning Errorlevel 8"

Environment:
Qlik Sense 3.1 SR2
QlikSense Automated Task Failure Email Alerts  - Version 1.4

Can you please help on this issue?

Best Regards,
K

**Comment by NickAkincilar** [comment]
Can you give a list of your failed task names? It sounds like there is a strange charter in the name.

**Comment by knightriderX3** [comment]
'TestEmailAlertNotification' is the name of the task that failed.

**Comment by knightriderX3** [comment]
[TestEmailAlertNotification.txt](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/778117/TestEmailAlertNotification.txt)
This is the log i downloaded from QMC for that task.

**Comment by NickAkincilar** [comment]
What is the QS version that is giving you the error?

**Comment by knightriderX3** [comment]
Qlik Sense 3.1 SR2

**Comment by NickAkincilar** [comment]
Try the following installer. Tool is using REST API to get data from QMC and does not use the txt log files. This version should log the JSON data that is causing the issue. Please install this, run the same test and attach the new log file which should have more info in it.

[Version 1.4a](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/blob/master/QlikSense_Email_Alerts_V1_4a.zip)

**Comment by knightriderX3** [comment]
Thanks a lot for the quick response.

Works like a charm!


:)
