### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rverfuurden** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#21]
When running the email alerts generated tis error in the log:
018_10_28_09_33_36,Error,"System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
[]"
Also there where no emails send

This hapens when there are no tasks with status failed but there are tasks with status aborted or error.

**Comment by rverfuurden** [comment]
I have sovled the error by changing the folowing in the program.cs (line 324 - 329)
old code:
` //***
string temp;
temp = qs.GetTaskByStatusText(QSTaskStatus.Failed);
List<TaskResult> MyTaskResult = JsonConvert.DeserializeObject<List<TaskResult>>(temp);
//****` 
New code:
`                    //***
                    //---Changed to also allow for reporting of error and abotred tasks
                    string TasksFailed;
                    TasksFailed = qs.GetTaskByStatusText(QSTaskStatus.Failed);
                    List<TaskResult> MyTaskResult = JsonConvert.DeserializeObject<List<TaskResult>>(TasksFailed);

                    string TasksError;
                    TasksError = qs.GetTaskByStatusText(QSTaskStatus.Error);
                    List<TaskResult> MyTaskResultError = JsonConvert.DeserializeObject<List<TaskResult>>(TasksError);

                    string TasksAborted;
                    TasksAborted = qs.GetTaskByStatusText(QSTaskStatus.Failed);
                    List<TaskResult> MyTaskResultAborted = JsonConvert.DeserializeObject<List<TaskResult>>(TasksAborted);
                                                        
                    MyTaskResult.AddRange(MyTaskResultError);
                    MyTaskResult.AddRange(MyTaskResultAborted);
                    //---


                    //string temp;
                    //temp = qs.GetTaskByStatusText(QSTaskStatus.Failed);
                    //List<TaskResult> MyTaskResult = JsonConvert.DeserializeObject<List<TaskResult>>(temp);
                    //****`
