### ISSUE TITLE
Internal Server Error: Failed to copy file.

### ISSUE THREAD

**Issue by petert-ometis** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#23]
Hi!

I've set version 1.4c of the tool, tested the connection to my QlikSense June2019.
Setup the tool to run as an admin user, same user that runs QlikSense, Root admin with full access to QS.

Tested email sending, the tool created the windows scheduler task and i can see it runs every 5mins.
But i don't get any alert emails, and the following in the logs...

2019_08_06_02_10_55,Information,"Proxy: https://qsdev01"
2019_08_06_02_10_55,Information,"Looking for Failed Tasks..."
2019_08_06_02_10_56,Information,"Found 3 Failed Tasks!"
2019_08_06_02_10_56,Error,"System.Exception: Internal Server Error: Failed to copy file.
   at QVnextDemoBuilder.QRSNTLMWebClient.Get(String endpoint, Dictionary`2 queries)
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetTaskFile(String Taskid, String FileRefID)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
[]"
2019_08_06_02_10_56,Information,"Returning Errorlevel 8"

**Comment by NickAkincilar** [comment]
Please look at the scheduled task properties and make sure it is setup to be executed as the userid that you used to install and configure it.

**Comment by petert-ometis** [comment]
Hello Nick,
Thanks for the reply.
I've checked the windows scheduled task and re-entered the username/password, the task runs and generates the new log file, but with the same error unfortunately.

I then tested with another of our QS servers, and was able to get the alert to work.
Both servers are QS June 2019 and i used the same username for both.
