### ISSUE TITLE
Multi node configuration Email task is throwing error when installed TLS12

### ISSUE THREAD

**Issue by sivajisrinivas** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#29]
initially when we configured email task failure was working with personal account and we changed the account with the QS installation account and it is failingwith the below error

,Error,"System.Exception: Internal Server Error: Failed to copy file.
   at QVnextDemoBuilder.QRSNTLMWebClient.Get(String endpoint, Dictionary`2 queries)
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetTaskFile(String Taskid, String FileRefID)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
and we copied VSproject files to the installation directory it is throwing the following error

Error,"System.Exception: Internal Server Error: Failed to copy file.
   at QVnextDemoBuilder.QRSNTLMWebClient.Get(String endpoint, Dictionary`2 queries) in C:\Users\ltu\Downloads\QlikSenseEmailAdmin_V14c_VS_Project\QlikSenseEmailAdmin\QRSNTLMWebClient.cs:line 205
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetTaskFile(String Taskid, String FileRefID) in C:\Users\ltu\Downloads\QlikSenseEmailAdmin_V14c_VS_Project\QlikSenseEmailAdmin\QlikSenseJSONHelper.cs:line 185
   at QlikSenseEmailAdmin.Program.Main(String[] args) in C:\Users\ltu\Downloads\QlikSenseEmailAdmin_V14c_VS_Project\QlikSenseEmailAdmin\Program.cs:line 438
[]"

now both personal account or service account getting same error.

**Comment by NickAkincilar** [comment]
I can no longer have access to QlikSense environment and can support the code.  For TLS 12 error, please check.

https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/issues/24

**Comment by NickAkincilar** [comment]
FYI...the code failing seems to fetch a log file from QlikSense API as a string and not trying to save it to disk. My guess is QlikSense is failing to create the log file on the server side. I would try logging in to QMC using the same windows user that is running this email task and try to download a task log file directly from QMC to see if that works.

**Comment by sivajisrinivas** [comment]
it is the service account which we used to install the qliksense and it was sending couple of mails and after that it is throwing error. on the server i tried the steps you mentioned and it was able to download the logs. we tried in another server and there also same issue.

**Comment by sivajisrinivas** [comment]
Nick,
 we found what the issue is after check the visual studio code, we were opening the logs of each task in QMC and found that one of the task does not have log file after failing. some how QMC was not able to find the script log for particular task and the email task was trying to copy/find the same file and failing.

we reran the same task now and got log in QMC. finally issue got resolved.

may be some code change is required to skip those kind of issues.

any way thanks for looking into the issue.

**Comment by nitin881984** [comment]
HI Sivajisrinivas,

What was the solution you got to resolve the issue as after installing TLS 1.2, it went of in my case too.
