### ISSUE TITLE
Email alerts are not generating  -  Getting "Error,"System.Exception: Internal Server Error: Failed to copy file." in logs

### ISSUE THREAD

**Issue by Ezhil0000** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#35]
Hi Team,
Recently the users are not receiving the alerts mail and we are seeing the below error in our history logs. Kindly help us in checking the issue.
Time, LogLevel, Message
2024_01_31_07_08_02,Information,"Proxy: http://localhost/windows"
2024_01_31_07_08_02,Information,"Looking for Failed Tasks..."
2024_01_31_07_08_45,Information,"Found 99 Failed Tasks!"
2024_01_31_07_08_47,Error,"System.Exception: Internal Server Error: Failed to copy file.
   at QVnextDemoBuilder.QRSNTLMWebClient.Get(String endpoint, Dictionary`2 queries)
   at QlikSenseJSONObjects.QlikSenseJSONHelper.GetTaskFile(String Taskid, String FileRefID)
   at QlikSenseEmailAdmin.Program.Main(String[] args)
[]"
2024_01_31_07_08_47,Information,"Returning Errorlevel 8"

Thanks & Regards,
Ezhil

**Comment by ShalakaKshirsagar** [comment]
Hello, any reply to above comment ? I am also facing the same error..
